### ISSUE TITLE
piREST problem

### ISSUE THREAD

**Issue by hellzakk** [marcoschwartz/aREST#113]
Hi, when i try to run the example with

$ node app.js

i got the following error

/home/pi/test/app.js:5
<!DOCTYPE html>
^

SyntaxError: Unexpected token <
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

any hint?

Last question, it's possible to implement with meteor (meteor.com)?

**Comment by marcoschwartz** [comment]
Hello, this would be more for the pi-aREST repo :) However, please get in touch directly via email about your issue: contact@arest.io. Thanks!
